### ISSUE TITLE
Brand change to EcoUniversalLandControl

### ISSUE THREAD

**Issue by StallEF** [Eco-Russian-Community/WorldEdit#16]
- [ ] rename all classes to EULC + function.CS
- [ ] rename commands to /lc + short
- [ ] rename repository to EcoUniversalLandControl

**Comment by TheKye** [comment]
Yeah sorry, i can't let you rebrand the plugin based off a fork. you need to build your own version from scratch that doesn't use any of the methods or functions from the source version. 

should you wish to continue to develop the world edit plugin, @Tavren may do so on the main repo.

**Comment by Tavren** [comment]
im not go to work with you or on your version of the plugin

we ask to work on it before start to work on own and you not respond, now it's late

we not need your permission to fork, modify and release own versions as you have no license what restrict us from that or any mentioned rules in your repository and we keep the back link to you as the base of our version

and if we decide to the rebranding of OUR version where we modify more than half of the code, we can do that and we not going to ask you

if you want so much, we can remove the link to your repository and make our version to be not forked from yours. if you want that @TheKye

**Comment by TheKye** [comment]
I have just been informed, the original creator released the mod under german law, which means, even though no license was given, all rights are reserved to the original creator, which means you cannot redistribute a modified version without their permission.

**Comment by Tavren** [comment]
> 
> 
> I have just been informed, the original creator released the mod under german law, which means, even though no license was given, all rights are reserved to the original creator, which means you cannot redistribute a modified version without their permission.

give me please something what proof of allowance from @lordmampf for you to take his mod without fork it from his original repository https://github.com/EcoModsDevelopers/EcoWorldEdit and redistribute modified version of it

**Comment by Tavren** [comment]
> please tell me how i didn't respond. i did.

as i know after source provided, we wait the response about access for repository for 4 days, and that what i mean when say you not respond

**Comment by TheKye** [comment]
i don't actually need to provide you with that, as thats not the issue here.

but this is all i have left to say. 
I told stal to make a pull request to have it merged, and if you insist on continuing this endeavor the Eco Modding Community will no longer support the ERC devs as this not okay. it is not okay to take works of someone else, make modifications and release it as something else, we will be making sure other moders are aware that this practice is not okay, because its not.

now you can decide what you do.

**Comment by TheKye** [comment]
> > please tell me how i didn't respond. i did.
> 
> as i know after source provided, we wait the response about access for repository for 4 days, and that what i mean when say you not respond

i clearly said, create a pr ( which is a pull request) to the we repo the SAME day stal reached out to me. there was no 4 days inbetween, it was the same day. plus i also have a life outside of modding which means i can't always respond to things when its convenient for the person asking the question

**Comment by Tavren** [comment]
> 
> 
> i don't actually need to provide you with that, as thats not the issue here.
> 
> but this is all i have left to say.
> I told stal to make a pull request to have it merged, and if you insist on continuing this endeavor the Eco Modding Community will no longer support the ERC devs as this not okay. it is not okay to take works of someone else, make modifications and release it as something else, we will be making sure other moders are aware that this practice is not okay, because its not.
> 
> now you can decide what you do.

glad we figure out that the rights not the issue here
now, according to #8 you said that 2 different version is not right with same name that why we decide to rename our version
please decide what you want, and again, we have original author same as you as original authors, we not use your framework. Would you want to say that we and anyone else not able to make any modification to worldedit?  

As of Eco Modding Community, i would like them all to see this issue what are raise from nowhere just because we making progress in something but going the other way and that no one allowed to fork code and change it and allow others to use what we make. That would be a good warn for any who want to do something around Eco, that they not allowed to do that.

**Comment by TheKye** [comment]
okay lets cut to the chase.

The modding community doesn't want people thinking it is okay to modify someones work and pass it as your own.

Secondly, what do you have to gain from this entire thing? 

Why feel the need to rebrand when you could help develop what is already there? 

using em framework has nothing to do with it, i used that simply because it has tools in it to make things easier while reducing mod conflicts. that's the point of it.

my goal here was not to cause a massive conflict, but to point out that you can't just rename someones work because you changed some internal workings, to point out what you have done here could have been put into the plugin that was already working, the same plugin that you improved and fixed some present issuea in,

it would have been more beneficial to merge the projects, i was actually working on creating a local merge of both work to submit to the main branch so we could work on it together, as i really liked your work and was happy with it, now this has blown out of the water due to what? someone not relaying information?

its time to take a step back and work out where we go from here.

**Comment by Tavren** [comment]
We never present someone work as own and that mentioned in readme and project files and that why this repo is forked from yours, not created empty with the code pasted in it, so it always have the link to you as the source for our modifications.

Ok, why we want our version?

1. Because of the framework, we not want use it at all for importing/exporting, that the first case why we develop own version with own format we going to support.
2. We have own view of things and as the time show that not related to your view. as example - directory for save the files and im not want to debate about things as i work with the @StallEF  and we discuss that and many other things.
3. We need full access to tickets, wiki and other things if me and @StallEF  works on that actively and as a team
4. We not want to hang for weeks to have permission for do something/change something/add someone to repository if we need it, and so on - that hold the work.

So that why we made a fork and start work on that. We not restrict anyone, include you to use our code (i  meant things we write/rewrite/optimize and so on) in your project if you want - but that up to you.

**Comment by TheKye** [comment]
i had already said i was happy to give you full access on there,

i use the em framework for importing and exporting because its an independent system that doesn't rely on the slg serializer as thats what kept breaking the we schematics in the first place, it relys soley on json serializer that is highly versatile,

also my reasoning for the schematics being in the configs folder and not the mods folder, there are 2:

first. Protection against mod folder deletion, their files are kept safe 

Second. they are a data file not a mod, they shouldn't be in the mods folder,

i do things the way i do for ease of use on the person using and the person making, 

i am nearly always around, i work at my computer, if someone needs something i can usually find the time to help them out, even if its to answer a question.

but from what i have seen, communication is an issue that needs to be addressed

**Comment by Tavren** [comment]
same as my goal is to make life easy for who will use it, i guess that why we even doing that

if you see, we use Json and that be the first thing is to leave from Eco serializer to be independed and flexible

and still, what we going to do with the different view on things?

**Comment by Tavren** [comment]
and about the folder, right mods folder maybe not the right place (also as SLG mentioned, UserCode folder will not be overwritten anymore) but as you correctly pointed, it's data files and fully not suited and related to config
more correctly and perfect location will be Storage location

**Comment by TheKye** [comment]
thats what discussions and compromises are for, work out if its worth doing, how its going to be beneficial and finding out if there is a better way to do it, 

like im the lead and creator of the em pack, but i don't limit my team or tell them we can't do something, if you have seen me around the discords i am always interested in peoples ideas, feedback and improvement suggestions most of which always get implemented, 

i am usually a very easy going person, its just this whole situation got me riled up as i am a strong believer of protecting peoples work, and that is why my first suggestion nearly every time has been to merge your work into the main repo,

you have done fantastic work on your upgrades and fixes and its not something i wanted to goto waste, but at the same time i also have a duty to protect the original creators work and prevent rebranding because to me, its not right, 

one other thing comes to mind, but it will be a pain,

merge your work here into the main repo in a separate branch, you can continue to build it free of dependencies and it can be released as a standalone version, while also helping me to get the main branch supporting both formats 

or 

even improving the overall main branch to a point where it can run effectively and efficiently without using any dependencies and without issues using what you have already started with, i will also be able to give you access to updating the pages where the plugin is released so when you feel its ready to be released and im not about you can also release the update

**Comment by TheKye** [comment]
> and about the folder, right mods folder maybe not the right place (also as SLG mentioned, UserCode folder will not be overwritten anymore) but as you correctly pointed, it's data files and fully not suited and related to config
> more correctly and perfect location will be Storage location

mm storage may be a better spot, some service providers may wipe that folder on server world regen though :/ some also limit the ability to creat additional parent folders which makes it difficult as well

**Comment by Tavren** [comment]
> even improving the overall main branch to a point where it can run effectively and efficiently without using any dependencies and without issues using what you have already started with, i will also be able to give you access to updating the pages where the plugin is released so when you feel its ready to be released and im not about you can also release the update

so, your proposition if i understand correct

- me and @StallEF  will have full access to your WorldEdit repository
- we merge our code into main branch without using framework
- we can do our work, create branches if need and so on
- we can make release

is that correct? Also maybe talk in the Discord?

**Comment by TheKye** [comment]
> > even improving the overall main branch to a point where it can run effectively and efficiently without using any dependencies and without issues using what you have already started with, i will also be able to give you access to updating the pages where the plugin is released so when you feel its ready to be released and im not about you can also release the update
> 
> so, your proposition if i understand correct
> 
> * me and @StallEF  will have full access to your WorldEdit repository
> * we merge our code into main branch without using framework
> * we can do our work, create branches if need and so on
> * we can make release
> 
> is that correct? Also maybe talk in the Discord?

That is correct, i am all for improving the plugin, even without using the framework, as i said i only used it so i didn't need to write a custom serializer or rely on the slg one

**Comment by TheKye** [comment]
also, if you don't mind me asking, why are you against using the framework?

**Comment by Tavren** [comment]
> also, if you don't mind me asking, why are you against using the framework?

because it do work behind my back and i not know what and how and as the goal here is to be flexible and able to not only provide server independent import and export but also allow to import files created in previous version of Eco (Migration) for that i need the control of how things will going to be serialized and deserialized and handle that same as not all things NewtonSoftJson can handle self. Other thing as the compression, write to actual file and other thing not bother me so i give that work to libraries.

**Comment by TheKye** [comment]
thats fair enough,

**Comment by Tavren** [comment]
> That is correct, i am all for improving the plugin, even without using the framework, as i said i only used it so i didn't need to write a custom serializer or rely on the slg one

allright, then @StallEF going to test the things what are ready, im going to reformat into format of your repository, you give us access and we transfer not closed tickets and merge the code, after that we close this repo, for communication @StallEF create talk in Discord

**Comment by TheKye** [comment]
Okay, i have sent both invites to the repo, you should have full access now
